version: 2

updates:
  - package-ecosystem: npm
    directory: /
    exclude-paths:
      - vendor/**
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Tokyo

  - package-ecosystem: uv
    directory: /python/sdk
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Tokyo

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Tokyo
