/** Canonical English documentation published from the repository. */
export type DocsLocale = string
export type DocsSidebar = string

export interface DocsPage {
  locale: DocsLocale
  contentLocale: string
  source: string
  route: string
  label: string
  sidebar: DocsSidebar | null
  section: string
  order: number
  outline?: number | readonly [number, number] | 'deep' | false
  sourceAliases?: string[]
}

export interface DocsSection {
  label: string
  collapsed?: boolean
}

export const localeCollections: Record<DocsLocale, readonly DocsSidebar[]> = {
  root: ['en-guide', 'en-develop', 'en-reference'],
}

const sections: readonly DocsSection[] = [
  { label: 'Guide' },
  { label: 'SDK' },
  { label: 'Automation' },
  { label: 'Integrations' },
  { label: 'Basics' },
  { label: 'Framework' },
  { label: 'Practice' },
  { label: 'Cordis framework tutorial' },
  { label: 'Concepts' },
  { label: 'Generated reference' },
  { label: 'Cordis Core API' },
  { label: 'Cookbook' },
  { label: 'Overview' },
  { label: 'Core and scopes', collapsed: true },
  { label: 'Sessions and persistence', collapsed: true },
  { label: 'Model and context', collapsed: true },
  { label: 'Execution and tools', collapsed: true },
  { label: 'Policy and interaction', collapsed: true },
  { label: 'Platform and access', collapsed: true },
]

export function sectionSpec(locale: DocsLocale, label: string): DocsSection & { index: number } {
  const section = locale === 'root' ? sections.find(candidate => candidate.label === label) : undefined
  if (section === undefined) throw new Error(`Sidebar section "${label}" has no placement in the ${locale} locale.`)
  return { ...section, index: sections.indexOf(section) }
}

const sourcePages: Omit<DocsPage, 'locale' | 'contentLocale'>[] = [
  {
    source: 'docs/user/index.md',
    route: 'index.md',
    label: 'DeepSeek Harness',
    sidebar: null,
    section: 'Home',
    order: 0,
  },
  {
    source: 'docs/user/guide/index.md',
    route: 'guide/quickstart.md',
    label: 'Use the Web UI',
    sidebar: 'en-guide',
    section: 'Guide',
    order: 1,
    sourceAliases: ['docs/user/guide'],
  },
  {
    source: 'docs/user/guide/providers.md',
    route: 'guide/providers.md',
    label: 'Configure models',
    sidebar: 'en-guide',
    section: 'Guide',
    order: 2,
  },
  {
    source: 'docs/user/guide/network-proxy.md',
    route: 'guide/network-proxy.md',
    label: 'Network proxy',
    sidebar: 'en-guide',
    section: 'Guide',
    order: 3,
  },
  {
    source: 'docs/user/guide/public-deployments.md',
    route: 'guide/public-deployments.md',
    label: 'Public deployments',
    sidebar: 'en-guide',
    section: 'Guide',
    order: 4,
  },
  {
    source: 'docs/user/guide/python-sdk.md',
    route: 'guide/python-sdk.md',
    label: 'Python',
    sidebar: 'en-guide',
    section: 'SDK',
    order: 1,
  },
  {
    source: 'docs/user/guide/github-review.md',
    route: 'guide/github-review.md',
    label: 'GitHub review sessions',
    sidebar: 'en-guide',
    section: 'Automation',
    order: 1,
  },
  {
    source: 'docs/user/guide/schedule.md',
    route: 'guide/schedule.md',
    label: 'Session reminders',
    sidebar: 'en-guide',
    section: 'Automation',
    order: 2,
  },
  {
    source: 'docs/user/guide/mcp-memory.md',
    route: 'guide/mcp-memory.md',
    label: 'Memory MCP',
    sidebar: 'en-guide',
    section: 'Integrations',
    order: 1,
  },
  {
    source: 'docs/user/develop/basic/index.md',
    route: 'develop/basic/index.md',
    label: 'Your first Harness plugin',
    sidebar: 'en-develop',
    section: 'Basics',
    order: 1,
    sourceAliases: ['docs/user/develop/basic'],
  },
  {
    source: 'docs/user/develop/basic/tool.md',
    route: 'develop/basic/tool.md',
    label: 'Build a tool',
    sidebar: 'en-develop',
    section: 'Basics',
    order: 2,
  },
  {
    source: 'docs/user/develop/basic/config.md',
    route: 'develop/basic/config.md',
    label: 'Plugin configuration',
    sidebar: 'en-develop',
    section: 'Basics',
    order: 3,
  },
  {
    source: 'docs/user/develop/basic/publish.md',
    route: 'develop/basic/publish.md',
    label: 'Package and install',
    sidebar: 'en-develop',
    section: 'Basics',
    order: 4,
  },
  {
    source: 'docs/user/develop/framework/index.md',
    route: 'develop/framework/index.md',
    label: 'Plugin lifecycle',
    sidebar: 'en-develop',
    section: 'Framework',
    order: 1,
    sourceAliases: ['docs/user/develop/framework'],
  },
  {
    source: 'docs/user/develop/framework/service.md',
    route: 'develop/framework/service.md',
    label: 'Services and dependencies',
    sidebar: 'en-develop',
    section: 'Framework',
    order: 2,
  },
  {
    source: 'docs/user/develop/framework/events.md',
    route: 'develop/framework/events.md',
    label: 'Event system',
    sidebar: 'en-develop',
    section: 'Framework',
    order: 3,
  },
  {
    source: 'docs/user/develop/practice/index.md',
    route: 'develop/practice/index.md',
    label: 'Capability layering',
    sidebar: 'en-develop',
    section: 'Practice',
    order: 1,
    sourceAliases: ['docs/user/develop/practice'],
  },
  {
    source: 'docs/user/develop/practice/llm-adapter.md',
    route: 'develop/practice/llm-adapter.md',
    label: 'LLM adapter',
    sidebar: 'en-develop',
    section: 'Practice',
    order: 2,
  },
  {
    source: 'docs/user/develop/practice/dynamic-cordis.md',
    route: 'develop/practice/dynamic-cordis.md',
    label: 'Persistent Harness plugins',
    sidebar: 'en-develop',
    section: 'Practice',
    order: 3,
  },
  {
    source: 'docs/cordis-tutorial/index.md',
    route: 'develop/cordis-tutorial/index.md',
    label: 'Overview',
    sidebar: 'en-develop',
    section: 'Cordis framework tutorial',
    order: 0,
    sourceAliases: ['docs/cordis-tutorial'],
  },
  {
    source: 'docs/cordis-tutorial/01-first-plugin.md',
    route: 'develop/cordis-tutorial/01-first-plugin.md',
    label: '1. Your first plugin',
    sidebar: 'en-develop',
    section: 'Cordis framework tutorial',
    order: 1,
  },
  {
    source: 'docs/cordis-tutorial/02-lifecycle-and-effects.md',
    route: 'develop/cordis-tutorial/02-lifecycle-and-effects.md',
    label: '2. Lifecycle and effects',
    sidebar: 'en-develop',
    section: 'Cordis framework tutorial',
    order: 2,
  },
  {
    source: 'docs/cordis-tutorial/03-services.md',
    route: 'develop/cordis-tutorial/03-services.md',
    label: '3. Services',
    sidebar: 'en-develop',
    section: 'Cordis framework tutorial',
    order: 3,
  },
  {
    source: 'docs/cordis-tutorial/04-events.md',
    route: 'develop/cordis-tutorial/04-events.md',
    label: '4. Events',
    sidebar: 'en-develop',
    section: 'Cordis framework tutorial',
    order: 4,
  },
  {
    source: 'docs/cordis-tutorial/05-config.md',
    route: 'develop/cordis-tutorial/05-config.md',
    label: '5. Configuration',
    sidebar: 'en-develop',
    section: 'Cordis framework tutorial',
    order: 5,
  },
  {
    source: 'docs/cordis-tutorial/06-composition-and-hmr.md',
    route: 'develop/cordis-tutorial/06-composition-and-hmr.md',
    label: '6. Composition and HMR',
    sidebar: 'en-develop',
    section: 'Cordis framework tutorial',
    order: 6,
  },
  {
    source: 'docs/cordis-tutorial/07-into-the-harness.md',
    route: 'develop/cordis-tutorial/07-into-the-harness.md',
    label: '7. Into the harness',
    sidebar: 'en-develop',
    section: 'Cordis framework tutorial',
    order: 7,
  },
  {
    source: 'docs/cordis-primer.md',
    route: 'reference/cordis-primer.md',
    label: 'Cordis primer',
    sidebar: 'en-reference',
    section: 'Concepts',
    order: 1,
  },
  {
    source: 'docs/subsystems/README.md',
    route: 'reference/subsystems/index.md',
    label: 'Subsystems',
    sidebar: 'en-reference',
    section: 'Overview',
    order: 0,
    outline: [2, 3],
    sourceAliases: ['docs/subsystems'],
  },
  {
    source: 'docs/subsystems/core.md',
    route: 'reference/subsystems/core.md',
    label: 'Core',
    sidebar: 'en-reference',
    section: 'Core and scopes',
    order: 0,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/scope.md',
    route: 'reference/subsystems/scope.md',
    label: 'Scopes',
    sidebar: 'en-reference',
    section: 'Core and scopes',
    order: 1,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/session.md',
    route: 'reference/subsystems/session.md',
    label: 'Sessions',
    sidebar: 'en-reference',
    section: 'Sessions and persistence',
    order: 0,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/session-query.md',
    route: 'reference/subsystems/session-query.md',
    label: 'Session query',
    sidebar: 'en-reference',
    section: 'Sessions and persistence',
    order: 1,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/session-reference.md',
    route: 'reference/subsystems/session-reference.md',
    label: 'Session references',
    sidebar: 'en-reference',
    section: 'Sessions and persistence',
    order: 2,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/session-title.md',
    route: 'reference/subsystems/session-title.md',
    label: 'Session titles',
    sidebar: 'en-reference',
    section: 'Sessions and persistence',
    order: 3,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/session-projection.md',
    route: 'reference/subsystems/session-projection.md',
    label: 'Session projections',
    sidebar: 'en-reference',
    section: 'Sessions and persistence',
    order: 4,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/persistence.md',
    route: 'reference/subsystems/persistence.md',
    label: 'Session persistence',
    sidebar: 'en-reference',
    section: 'Sessions and persistence',
    order: 5,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/spill.md',
    route: 'reference/subsystems/spill.md',
    label: 'Spill storage',
    sidebar: 'en-reference',
    section: 'Sessions and persistence',
    order: 6,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/session-telemetry.md',
    route: 'reference/subsystems/session-telemetry.md',
    label: 'SessionTelemetryBackend',
    sidebar: 'en-reference',
    section: 'Sessions and persistence',
    order: 7,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/llm-streaming.md',
    route: 'reference/subsystems/llm-streaming.md',
    label: 'LLM streaming',
    sidebar: 'en-reference',
    section: 'Model and context',
    order: 0,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/token-meter.md',
    route: 'reference/subsystems/token-meter.md',
    label: 'Token metering',
    sidebar: 'en-reference',
    section: 'Model and context',
    order: 1,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/system-prompt.md',
    route: 'reference/subsystems/system-prompt.md',
    label: 'System prompts',
    sidebar: 'en-reference',
    section: 'Model and context',
    order: 2,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/compaction.md',
    route: 'reference/subsystems/compaction.md',
    label: 'Compaction',
    sidebar: 'en-reference',
    section: 'Model and context',
    order: 3,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/tools.md',
    route: 'reference/subsystems/tools.md',
    label: 'Tools',
    sidebar: 'en-reference',
    section: 'Execution and tools',
    order: 0,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/shell.md',
    route: 'reference/subsystems/shell.md',
    label: 'Bash execution',
    sidebar: 'en-reference',
    section: 'Execution and tools',
    order: 1,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/subprocess.md',
    route: 'reference/subsystems/subprocess.md',
    label: 'Subprocesses',
    sidebar: 'en-reference',
    section: 'Execution and tools',
    order: 2,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/terminal.md',
    route: 'reference/subsystems/terminal.md',
    label: 'PTY sessions',
    sidebar: 'en-reference',
    section: 'Execution and tools',
    order: 3,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/jobs.md',
    route: 'reference/subsystems/jobs.md',
    label: 'Background jobs',
    sidebar: 'en-reference',
    section: 'Execution and tools',
    order: 4,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/filesystem.md',
    route: 'reference/subsystems/filesystem.md',
    label: 'Filesystem',
    sidebar: 'en-reference',
    section: 'Execution and tools',
    order: 5,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/lsp.md',
    route: 'reference/subsystems/lsp.md',
    label: 'LSP navigation',
    sidebar: 'en-reference',
    section: 'Execution and tools',
    order: 6,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/ptc-runtime.md',
    route: 'reference/subsystems/ptc-runtime.md',
    label: 'PTC runtime',
    sidebar: 'en-reference',
    section: 'Execution and tools',
    order: 7,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/web.md',
    route: 'reference/subsystems/web.md',
    label: 'Web access',
    sidebar: 'en-reference',
    section: 'Execution and tools',
    order: 8,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/skills.md',
    route: 'reference/subsystems/skills.md',
    label: 'Skills',
    sidebar: 'en-reference',
    section: 'Execution and tools',
    order: 9,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/workflow.md',
    route: 'reference/subsystems/workflow.md',
    label: 'Workflows',
    sidebar: 'en-reference',
    section: 'Execution and tools',
    order: 10,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/subagent.md',
    route: 'reference/subsystems/subagent.md',
    label: 'Subagents',
    sidebar: 'en-reference',
    section: 'Execution and tools',
    order: 11,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/approval.md',
    route: 'reference/subsystems/approval.md',
    label: 'Approvals',
    sidebar: 'en-reference',
    section: 'Policy and interaction',
    order: 0,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/permission-presets.md',
    route: 'reference/subsystems/permission-presets.md',
    label: 'Permission presets',
    sidebar: 'en-reference',
    section: 'Policy and interaction',
    order: 1,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/sandbox.md',
    route: 'reference/subsystems/sandbox.md',
    label: 'Sandboxing',
    sidebar: 'en-reference',
    section: 'Policy and interaction',
    order: 2,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/plan.md',
    route: 'reference/subsystems/plan.md',
    label: 'Plan mode',
    sidebar: 'en-reference',
    section: 'Policy and interaction',
    order: 3,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/user-questions.md',
    route: 'reference/subsystems/user-questions.md',
    label: 'User interaction',
    sidebar: 'en-reference',
    section: 'Policy and interaction',
    order: 4,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/commands.md',
    route: 'reference/subsystems/commands.md',
    label: 'Human commands',
    sidebar: 'en-reference',
    section: 'Policy and interaction',
    order: 5,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/goal.md',
    route: 'reference/subsystems/goal.md',
    label: 'Goals',
    sidebar: 'en-reference',
    section: 'Policy and interaction',
    order: 6,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/schedule.md',
    route: 'reference/subsystems/schedule.md',
    label: 'Scheduled reminders',
    sidebar: 'en-reference',
    section: 'Policy and interaction',
    order: 7,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/web-server.md',
    route: 'reference/subsystems/web-server.md',
    label: 'HTTP server',
    sidebar: 'en-reference',
    section: 'Platform and access',
    order: 0,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/web-client.md',
    route: 'reference/subsystems/web-client.md',
    label: 'Web Client architecture',
    sidebar: 'en-reference',
    section: 'Platform and access',
    order: 1,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/client-modules.md',
    route: 'reference/subsystems/client-modules.md',
    label: 'Client modules',
    sidebar: 'en-reference',
    section: 'Platform and access',
    order: 2,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/slots.md',
    route: 'reference/subsystems/slots.md',
    label: 'Client slots',
    sidebar: 'en-reference',
    section: 'Platform and access',
    order: 3,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/client-resources.md',
    route: 'reference/subsystems/client-resources.md',
    label: 'Client resources',
    sidebar: 'en-reference',
    section: 'Platform and access',
    order: 4,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/sidebar-right.md',
    route: 'reference/subsystems/sidebar-right.md',
    label: 'Right Sidebar',
    sidebar: 'en-reference',
    section: 'Platform and access',
    order: 5,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/conversation.md',
    route: 'reference/subsystems/conversation.md',
    label: 'Conversation assembly',
    sidebar: 'en-reference',
    section: 'Platform and access',
    order: 6,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/typert.md',
    route: 'reference/subsystems/typert.md',
    label: 'Typert',
    sidebar: 'en-reference',
    section: 'Platform and access',
    order: 7,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/storage.md',
    route: 'reference/subsystems/storage.md',
    label: 'Storage',
    sidebar: 'en-reference',
    section: 'Platform and access',
    order: 8,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/workspace.md',
    route: 'reference/subsystems/workspace.md',
    label: 'Workspaces',
    sidebar: 'en-reference',
    section: 'Platform and access',
    order: 9,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/settings.md',
    route: 'reference/subsystems/settings.md',
    label: 'User settings',
    sidebar: 'en-reference',
    section: 'Platform and access',
    order: 10,
    outline: [2, 3],
  },
  {
    source: 'docs/subsystems/credentials.md',
    route: 'reference/subsystems/credentials.md',
    label: 'User credentials',
    sidebar: 'en-reference',
    section: 'Platform and access',
    order: 11,
    outline: [2, 3],
  },
  {
    source: 'docs/architecture.md',
    route: 'reference/index.md',
    label: 'Architecture',
    sidebar: 'en-reference',
    section: 'Concepts',
    order: 0,
  },
  {
    source: 'docs/capability-seams.md',
    route: 'reference/capability-seams.md',
    label: 'Capability services',
    sidebar: 'en-reference',
    section: 'Concepts',
    order: 2,
  },
  {
    source: 'docs/agent-lifecycle.md',
    route: 'reference/agent-lifecycle.md',
    label: 'Agent lifecycle',
    sidebar: 'en-reference',
    section: 'Concepts',
    order: 3,
  },
  {
    source: 'docs/tool-execution-pipeline.md',
    route: 'reference/tool-execution-pipeline.md',
    label: 'Tool execution',
    sidebar: 'en-reference',
    section: 'Concepts',
    order: 4,
  },
  {
    source: 'docs/api-gateway.md',
    route: 'reference/api-gateway.md',
    label: 'API Gateway',
    sidebar: 'en-reference',
    section: 'Concepts',
    order: 5,
  },
  {
    source: 'docs/config-catalog.md',
    route: 'reference/config-catalog.md',
    label: 'Plugin configuration',
    sidebar: 'en-reference',
    section: 'Generated reference',
    order: 0,
  },
  {
    source: 'docs/tool-catalog.md',
    route: 'reference/tool-catalog.md',
    label: 'Tool schemas',
    sidebar: 'en-reference',
    section: 'Generated reference',
    order: 1,
  },
  {
    source: 'docs/persistence-catalog.md',
    route: 'reference/persistence-catalog.md',
    label: 'Persistence events',
    sidebar: 'en-reference',
    section: 'Generated reference',
    order: 2,
    outline: 'deep',
  },
  {
    source: 'docs/cordis-api/context.md',
    route: 'reference/cordis-api/context.md',
    label: 'Context',
    sidebar: 'en-reference',
    section: 'Cordis Core API',
    order: 0,
  },
  {
    source: 'docs/cordis-api/events.md',
    route: 'reference/cordis-api/events.md',
    label: 'Events',
    sidebar: 'en-reference',
    section: 'Cordis Core API',
    order: 1,
  },
  {
    source: 'docs/cordis-api/fiber.md',
    route: 'reference/cordis-api/fiber.md',
    label: 'Fiber',
    sidebar: 'en-reference',
    section: 'Cordis Core API',
    order: 2,
  },
  {
    source: 'docs/cordis-api/registry.md',
    route: 'reference/cordis-api/registry.md',
    label: 'Plugin Registry',
    sidebar: 'en-reference',
    section: 'Cordis Core API',
    order: 3,
  },
  {
    source: 'docs/cordis-api/service.md',
    route: 'reference/cordis-api/service.md',
    label: 'Service',
    sidebar: 'en-reference',
    section: 'Cordis Core API',
    order: 4,
  },
  {
    source: 'docs/cordis-api/inherited.md',
    route: 'reference/cordis-api/inherited.md',
    label: 'Inherited surface',
    sidebar: 'en-reference',
    section: 'Cordis Core API',
    order: 5,
  },
  {
    source: 'docs/cookbook/adding-a-package.md',
    route: 'reference/cookbook/adding-a-package.md',
    label: 'Adding a package',
    sidebar: 'en-reference',
    section: 'Cookbook',
    order: 0,
  },
  {
    source: 'docs/cookbook/adding-a-tool.md',
    route: 'reference/cookbook/adding-a-tool.md',
    label: 'Adding a tool',
    sidebar: 'en-reference',
    section: 'Cookbook',
    order: 1,
  },
  {
    source: 'docs/cookbook/adding-an-llm-adapter.md',
    route: 'reference/cookbook/adding-an-llm-adapter.md',
    label: 'Adding an LLM adapter',
    sidebar: 'en-reference',
    section: 'Cookbook',
    order: 2,
  },
  {
    source: 'docs/cookbook/adding-a-settings-card.md',
    route: 'reference/cookbook/adding-a-settings-card.md',
    label: 'Adding a settings page',
    sidebar: 'en-reference',
    section: 'Cookbook',
    order: 3,
  },
  {
    source: 'docs/cookbook/extension-cookbook.md',
    route: 'reference/cookbook/extension-cookbook.md',
    label: 'Extension patterns',
    sidebar: 'en-reference',
    section: 'Cookbook',
    order: 4,
  },
]

export const docsPages: DocsPage[] = sourcePages.map(page => ({
  ...page,
  locale: 'root',
  contentLocale: 'en-US',
}))

export function orderedPages(locale: DocsLocale, collection: DocsSidebar): DocsPage[] {
  return docsPages.filter(page => page.locale === locale && page.sidebar === collection)
    .sort((a, b) => sectionSpec(locale, a.section).index - sectionSpec(locale, b.section).index || a.order - b.order)
}

export function routeLink(route: string): string {
  return `/${route.replace(/(?:index)?\.md$/, '')}`
}

export function landingLink(locale: DocsLocale, collection: DocsSidebar): string {
  const first = orderedPages(locale, collection)[0]
  if (first === undefined) throw new Error(`Sidebar collection "${collection}" publishes no page.`)
  return routeLink(first.route)
}
